### ISSUE TITLE
python smoke_taichi_gpu.py  error

### ISSUE THREAD

**Issue by lk1983823** [yuanming-hu/difftaichi#4] opened 2020-01-13 04:13 UTC
Error encountered when running  smoke_taichi_gpu.py
```

[Release mode]
[T 01/13/20 12:10:09.233] [logging.cpp:Logger@68] Taichi core started. Thread ID = 13909
[Taichi version 0.3.20, cuda 10.0, commit 1c85d8e1]
Loading initial and target states...
Using CUDA Device [0]: GeForce GTX 1080
Device Compute Capability: 6.1
[I 01/13/20 12:10:11.626] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: x86_64
[I 01/13/20 12:10:11.652] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/impl.py:materialize@125] Materializing layout...
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 700 promoted to 1024.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 700 promoted to 1024.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 100 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[D 01/13/20 12:10:11.652] [snode.cpp:create_node@48] Non-power-of-two node size 110 promoted to 128.
[I 01/13/20 12:10:11.769] [struct_llvm.cpp:operator()@276] Allocating data structure of size 235012104 B
Initializing runtime with 38 elements
Runtime initialized.
[I 01/13/20 12:10:11.777] [taichi_llvm_context.cpp:TaichiLLVMContext@59] Creating llvm context for arch: cuda
[I 01/13/20 12:10:12.048] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_0_...
[I 01/13/20 12:10:12.136] [llvm_jit_ptx.cpp:compile@179] PTX size: 26.97KB
[I 01/13/20 12:10:12.139] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_1_...
[I 01/13/20 12:10:12.227] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.229] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_2_...
[I 01/13/20 12:10:12.318] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.320] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_3_...
[I 01/13/20 12:10:12.408] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.410] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_4_...
[I 01/13/20 12:10:12.500] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.502] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_5_...
[I 01/13/20 12:10:12.590] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.592] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_6_...
[I 01/13/20 12:10:12.681] [llvm_jit_ptx.cpp:compile@179] PTX size: 27.06KB
[I 01/13/20 12:10:12.683] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_7_...
[I 01/13/20 12:10:12.759] [llvm_jit_ptx.cpp:compile@179] PTX size: 17.42KB
[I 01/13/20 12:10:12.761] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel clear_gradients_c26_8_...
[I 01/13/20 12:10:12.835] [llvm_jit_ptx.cpp:compile@179] PTX size: 16.25KB
[I 01/13/20 12:10:12.870] [/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lkconda/lib/python3.6/site-packages/taichi/lang/kernel.py:materialize@180] Compiling kernel advect_c10_0_...
[E 01/13/20 12:10:12.879] [type_check.cpp:visit@113] Taichi tensors must be accessed with integral indices (e.g., i32/i64). It seems that you have used a float point number as an index. You can cast that to an integer using int(). Also note that ti.floor(ti.f32) returns f32.
[E 01/13/20 12:10:12.879] Received signal 6 (Aborted)
***********************************
```
llvm version is 6.0.0
cuda 10
ubuntu 16.04
Thanks!

**Comment by yuanming-hu** [comment] 2020-01-13 04:15
Thanks for reporting. It seems to be caused by a recent Taichi update. I'm fixing it now.

**Comment by yuanming-hu** [comment] 2020-01-13 04:20
I believe this is fixed now with Taichi v0.3.21. Recently Taichi changed the semantics of `/` and `//`, which broke this script. Sorry about that. Please let me know if it works well on your end.

**Comment by lk1983823** [comment] 2020-01-13 05:20
I have updated the package by pip install taichi-nightly-cuda-10-0 --upgrade and find the version 0.3.21. But still  error:

```
[E 01/13/20 13:18:09.546] [type_check.cpp:visit@113] Taichi tensors must be accessed with integral indices (e.g., i32/i64). It seems that you have used a float point number as an index. You can cast that to an integer using int(). Also note that ti.floor(ti.f32) returns f32.
[E 01/13/20 13:18:09.546] Received signal 6 (Aborted)
```

**Comment by yuanming-hu** [comment] 2020-01-13 06:14
Hi Kuan, did you `git pull` difftaichi? `smoke_taichi_gpu.py` was also updated.

**Comment by lk1983823** [comment] 2020-01-21 08:50
Thank you. I git clone again. It works.

**Closed** 2020-01-21 08:50 UTC
